import { useEffect, useRef, useState, type FormEvent } from 'react';
import { MagnifyingGlass, UserCircle, House, ClockCounterClockwise, ArrowLeft, CheckCircle, XCircle, MinusCircle, Package, Plus, CaretRight, WarningCircle, Trash, PencilSimple } from '@phosphor-icons/react';

type Review = { buy: string; quality: string; expectation: string; value: string; reasons: Record<string,string>; comment: string };
type Product = { id: number; name: string; brand: string; amount: string; category: string; code: string; photo?: string; owned?: boolean; review?: Review };
const emptyReview = (): Review => ({ buy:'',quality:'',expectation:'',value:'',reasons:{},comment:'' });
const initial: Product[] = [
 { id:1,name:'Doritos Nacho Cheese',brand:'Doritos',amount:'84 g',category:'Alimentos',code:'7892840222949',photo:'doritos',review:{buy:'Não',quality:'Adequada',expectation:'Não atendeu',value:'Ruim',reasons:{Sabor:'Negativo','Textura / consistência':'Negativo'},comment:'Você avaliou como muito salgado e pouco crocante.'}},
 { id:2,name:'Leite Integral Itambé',brand:'Itambé',amount:'1 L',category:'Bebidas',code:'',photo:'milk',review:{buy:'Sim',quality:'Alta',expectation:'Atendeu',value:'Bom',reasons:{Sabor:'Positivo'},comment:'Você avaliou como saboroso e com ótima qualidade.'}},
 { id:3,name:'Cookies Bauducco Gotas de Chocolate',brand:'Bauducco',amount:'100 g',category:'Alimentos',code:'',photo:'cookies',review:{buy:'Talvez',quality:'Adequada',expectation:'Atendeu',value:'Justo',reasons:{Sabor:'Positivo'},comment:'Você achou gostoso, mas um pouco doce demais.'}},
 { id:4,name:'Doritos Nacho Cheese',brand:'Doritos',amount:'140 g',category:'Alimentos',code:'',photo:'doritos'},
 { id:5,name:'Café torrado e moído',brand:'Café da Serra',amount:'250 g',category:'Bebidas',code:'',owned:true}
];
const aspects=['Sabor','Cheiro / fragrância','Textura / consistência','Eficácia / desempenho','Quantidade / rendimento','Facilidade de uso / preparo','Embalagem','Durabilidade / conservação','Composição / ingredientes','Segurança / tolerância','Preço','Outro'];
function Badge({buy}:{buy:string}){const Icon=buy==='Sim'?CheckCircle:buy==='Não'?XCircle:MinusCircle;return <span className={`badge ${buy==='Sim'?'yes':buy==='Não'?'no':'maybe'}`}><Icon size={22} weight="fill"/><span>{buy==='Sim'?'Você compraria novamente':buy==='Não'?'Você não compraria novamente':'Talvez compraria novamente'}</span></span>;}
function Photo({product}:{product:Product}){return product.photo?<span className={`photo photo-${product.photo}`} role="img" aria-label={`Embalagem de ${product.name}`}></span>:<span className="no-photo"><Package size={32}/><small>Sem foto</small></span>;}
function validBarcode(code:string){if(!code)return true;if(!/^(\d{8}|\d{12}|\d{13}|\d{14})$/.test(code))return false;const digits=code.split('').map(Number);const check=digits.pop();return (10-digits.reverse().reduce((n,d,i)=>n+d*(i%2===0?3:1),0)%10)%10===check;}
export function MobilePrototype(){
 const [products,setProducts]=useState<Product[]>(initial);
 const [route,setRoute]=useState(location.hash.slice(1)||'home');
 const [query,setQuery]=useState('');const [submitted,setSubmitted]=useState('');const [mode,setMode]=useState('Nome');
 const [signed,setSigned]=useState(true);const [step,setStep]=useState(1);const [draft,setDraft]=useState<Review>(emptyReview);
 const [notice,setNotice]=useState('');const [error,setError]=useState('');const [network,setNetwork]=useState(false);const [failSave,setFailSave]=useState(false);
 const [deleteOpen,setDeleteOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const heading=useRef<HTMLHeadingElement>(null);
 const [destination,setDestination]=useState('home');const [editing,setEditing]=useState(false);const [duplicate,setDuplicate]=useState<Product>();
 const [productDraft,setProductDraft]=useState({name:'',brand:'',variant:'',quantity:'',unit:'g',category:'',code:''});
 useEffect(()=>{const update=()=>setRoute(location.hash.slice(1)||'home');window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update);},[]);
 useEffect(()=>{window.scrollTo(0,0);heading.current?.focus();setError('');},[route]);
 useEffect(()=>{if(deleteOpen)dialog.current?.showModal();else dialog.current?.close();},[deleteOpen]);
 const go=(next:string)=>{setNotice('');if(next!==route)location.hash=next;setError('');};
 const id=Number(route.split('/')[1]);const product=products.find(p=>p.id===id);
 const isReview=route.startsWith('review/');const isDetail=route.startsWith('product/');
 const requireSign=(next:string)=>{if(signed)go(next);else{setDestination(next);go('login');}};
 const startReview=(p:Product)=>{setEditing(!!p.review);setDraft(p.review?{...p.review,reasons:{...p.review.reasons}}:emptyReview());setStep(1);requireSign(`review/${p.id}`);};
 const back=()=>{if(isReview){if(step>1){setStep(step-1);setError('');return;}if(!window.confirm('Descartar o preenchimento desta avaliação?'))return;go(`product/${id}`);}else if(isDetail)go('search');else go('home');};
 const myReview=(p:Product)=>signed?p.review:undefined;
 const card=(p:Product)=><button key={p.id} className="product-row" onClick={()=>go(`product/${p.id}`)}><Photo product={p}/><span className="product-copy"><strong>{p.name}</strong><span className="meta">{p.brand} · {p.amount}</span>{myReview(p)?<><Badge buy={p.review!.buy}/><span className="comment">{p.review!.comment||'Veja os detalhes da sua experiência.'}</span></>:<span className="unreviewed">Você ainda não avaliou este produto <CaretRight size={16}/></span>}</span></button>;
 const submitProduct=(event:FormEvent)=>{event.preventDefault();setError('');setDuplicate(undefined);const d=productDraft;const quantity=Number(d.quantity.replace(',','.'));if(!Number.isFinite(quantity)||quantity<=0||(d.unit==='un'&&!Number.isInteger(quantity))||!/^[0-9]+([.,][0-9]{1,3})?$/.test(d.quantity)){setError('Informe uma quantidade positiva com até três casas decimais. Unidades devem ser inteiras.');return;}if(!validBarcode(d.code)){setError('Confira o código de barras e seu dígito verificador.');return;}const amount=`${quantity} ${d.unit}`;const same=products.find(p=>(d.code&&p.code===d.code)||(p.name.toLowerCase()===d.name.trim().toLowerCase()&&p.brand.toLowerCase()===d.brand.trim().toLowerCase()&&p.amount===amount));if(same){setDuplicate(same);return;}if(network){setError('Sem conexão. Seus campos foram mantidos.');return;}const p:Product={id:Math.max(...products.map(p=>p.id))+1,name:d.name.trim()+(d.variant.trim()?` · ${d.variant.trim()}`:''),brand:d.brand.trim(),amount,category:d.category,code:d.code,owned:true};setProducts(prev=>[p,...prev]);go(`product/${p.id}`);setNotice('Produto cadastrado na demonstração.');};
 const advance=()=>{setError('');if(step===1&&(!draft.buy||!draft.quality||!draft.expectation||!draft.value)){setError('Responda aos quatro critérios antes de continuar.');return;}if(step===2&&(!Object.keys(draft.reasons).length||Object.values(draft.reasons).some(v=>!v)||(draft.reasons.Outro&&!draft.comment.trim()))){setError('Escolha pelo menos um aspecto e sua percepção. “Outro” exige comentário.');return;}setStep(step+1);window.scrollTo(0,0);};
 const saveReview=()=>{if(!signed){setDestination(route);go('login');return;}if(failSave||network){setError('Não foi possível salvar. Suas respostas foram mantidas. Desative a falha no painel da prévia e tente novamente.');return;}setProducts(ps=>ps.map(p=>p.id===id?{...p,review:{...draft,reasons:{...draft.reasons}}}:p));go(`product/${id}`);setNotice(editing?'Avaliação atualizada na demonstração.':'Avaliação publicada na demonstração.');};
 const title=isDetail?'Produto':isReview?'Sua avaliação':route==='search'?'Buscar':route==='account'?'Minhas avaliações':route==='owned'?'Meus produtos':route==='new'?'Cadastrar produto':route==='login'?'Entrar na demonstração':'Merchant';
 return <div className="prototype-stage"><aside className="preview-label"><span>MERCHANT LAB</span> Prévia interativa · dados de exemplo</aside><div className="app-shell">
 <header className={route==='home'?'home-header':'page-header'}>{route!=='home'&&<button className="icon-button" aria-label="Voltar" onClick={back}><ArrowLeft size={24}/></button>}<div><h1 tabIndex={-1} ref={heading}>{title}</h1>{route==='home'&&<p>Suas compras, uma memória melhor</p>}</div>{route==='home'&&<button className="avatar" aria-label={signed?'Abrir minha conta':'Entrar'} onClick={()=>requireSign('account')}><UserCircle size={40} weight="fill"/></button>}</header>
 <main>{notice&&<div className="notice" role="status"><CheckCircle size={20}/>{notice}<button onClick={()=>setNotice('')} aria-label="Fechar aviso">OK</button></div>}
 {route==='home'&&<><button className="search-launch" onClick={()=>go('search')}><MagnifyingGlass size={26}/><span>Busque produto, marca ou código</span></button>{signed?<><section className="home-section"><h2>Lembrete para você</h2><p className="subtitle">Com base nas suas experiências anteriores</p>{products.filter(p=>p.review).slice(0,1).map(card)}{!products.some(p=>p.review)&&<div className="empty"><Package size={40}/><h3>Suas experiências vão aparecer aqui</h3><p>Encontre um produto que já experimentou.</p><button className="primary" onClick={()=>go('search')}>Buscar produto</button></div>}</section><section><h2>Avaliações recentes</h2><p className="subtitle">Produtos que você já avaliou</p>{products.filter(p=>p.review).slice(1,3).map(card)}</section></>:<section className="empty"><h2>Lembre do que vale comprar de novo.</h2><p>Consulte o catálogo e entre para registrar suas experiências.</p><button className="primary" onClick={()=>requireSign('account')}>Experimentar minha conta</button></section>}</>}
 {route==='search'&&<><form onSubmit={e=>{e.preventDefault();setSubmitted(query.trim());}}><fieldset className="segments"><legend>Buscar por</legend>{['Nome','Marca','Código'].map(m=><button type="button" key={m} className={mode===m?'selected':''} aria-pressed={mode===m} onClick={()=>{setMode(m);setQuery('');setSubmitted('');}}>{m}</button>)}</fieldset><label className="sr-only" htmlFor="search">{`Buscar por ${mode.toLowerCase()}`}</label><div className="search-field"><MagnifyingGlass size={24}/><input id="search" autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder={mode==='Código'?'Digite o código completo':'O que você está procurando?'} inputMode={mode==='Código'?'numeric':'search'} minLength={mode==='Código'?1:2}/><button aria-label="Executar busca"><CaretRight size={24}/></button></div></form>{network?<div className="empty"><WarningCircle size={40}/><h2>Não foi possível carregar</h2><p>Seus filtros foram mantidos.</p><button className="primary" onClick={()=>setNetwork(false)}>Tentar novamente</button></div>:<><div className="section-heading"><h2>{submitted?'Resultados':'Explore o catálogo'}</h2><span>{products.filter(p=>!submitted||(mode==='Código'?p.code===submitted:(mode==='Marca'?p.brand:p.name).toLocaleLowerCase().includes(submitted.toLocaleLowerCase()))).length} produtos</span></div>{products.filter(p=>!submitted||(mode==='Código'?p.code===submitted:(mode==='Marca'?p.brand:p.name).toLocaleLowerCase().includes(submitted.toLocaleLowerCase()))).map(card)}{submitted&&!products.some(p=>mode==='Código'?p.code===submitted:(mode==='Marca'?p.brand:p.name).toLocaleLowerCase().includes(submitted.toLocaleLowerCase()))&&<div className="empty"><MagnifyingGlass size={40}/><h3>Nenhum produto encontrado</h3><p>Tente outro termo ou cadastre o produto.</p><button className="secondary" onClick={()=>{setSubmitted('');setQuery('');}}>Limpar pesquisa</button></div>}</>}<button className="primary wide" onClick={()=>requireSign('new')}><Plus size={20}/>Cadastrar produto</button></>}
 {isDetail&&product&&<><div className="detail-product"><Photo product={product}/><div><h2>{product.name}</h2><p className="meta">{product.brand} · {product.amount}</p><span className="category">{product.category}</span></div></div><section className="detail-section"><h2>Sua avaliação</h2>{myReview(product)?<><Badge buy={product.review!.buy}/><p>{product.review!.comment}</p><dl>{[['Qualidade',product.review!.quality],['Expectativa',product.review!.expectation],['Custo-benefício',product.review!.value],...Object.entries(product.review!.reasons)].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><button className="secondary wide" onClick={()=>startReview(product)}><PencilSimple size={20}/>Editar avaliação</button><button className="text-button danger" onClick={()=>setDeleteOpen(true)}><Trash size={18}/>Excluir avaliação</button></>:<><p>{signed?'Você ainda não avaliou este produto.':'Entre para consultar ou registrar sua experiência.'}</p><button className="primary wide" onClick={()=>startReview(product)}>Avaliar produto</button></>}</section><section className="community"><h2>Comunidade</h2><p className="subtitle">Sem avaliações da comunidade neste exemplo.</p><p className="fine">Sua experiência aparece separada das opiniões de outras pessoas.</p></section></>}
 {isDetail&&!product&&<div className="empty"><h2>Produto indisponível</h2><button className="primary" onClick={()=>go('search')}>Voltar à busca</button></div>}
 {(route==='account'||route==='owned')&&<><div className="account-summary"><UserCircle size={40}/><div><strong>{signed?'Conta de demonstração':'Visitante'}</strong><p className="meta">Suas escolhas, do seu jeito.</p></div></div>{signed?<><div className="segments"><button className={route==='account'?'selected':''} onClick={()=>go('account')}>Minhas avaliações</button><button className={route==='owned'?'selected':''} onClick={()=>go('owned')}>Meus produtos</button></div>{products.filter(p=>route==='owned'?p.owned:p.review).map(card)}{!products.some(p=>route==='owned'?p.owned:p.review)&&<div className="empty"><Package size={36}/><h3>Nada por aqui ainda</h3><p>Encontre um produto para começar.</p></div>}<button className="primary wide" onClick={()=>go(route==='owned'?'new':'search')}>{route==='owned'?'Cadastrar produto':'Buscar produto'}</button><button className="text-button" onClick={()=>{setSigned(false);setDraft(emptyReview());setDestination('home');go('home');}}>Sair da demonstração</button></>:<button className="primary" onClick={()=>requireSign('account')}>Entrar na demonstração</button>}</>}
 {route==='login'&&<section className="empty"><UserCircle size={56} weight="duotone"/><h2>Vamos continuar?</h2><p>Esta prévia usa uma conta de exemplo. Você não precisa informar e-mail ou senha.</p><button className="primary wide" onClick={()=>{setSigned(true);go(destination);}}>Usar conta de demonstração</button><button className="text-button" onClick={()=>go('home')}>Continuar como visitante</button></section>}
 {route==='new'&&<form className="stack" onSubmit={submitProduct}><p className="subtitle">Primeiro o produto. Depois, sua experiência.</p>{(['name','brand','variant'] as const).map((k,i)=><label key={k}>{['Nome','Marca','Variante (opcional)'][i]}<input value={productDraft[k]} onChange={e=>setProductDraft({...productDraft,[k]:e.target.value})} required={k!=='variant'} minLength={k==='name'?2:1} maxLength={k==='name'?120:80}/></label>)}<div className="two-cols"><label>Quantidade<input inputMode="decimal" required value={productDraft.quantity} onChange={e=>setProductDraft({...productDraft,quantity:e.target.value})}/></label><label>Unidade<select value={productDraft.unit} onChange={e=>setProductDraft({...productDraft,unit:e.target.value})}>{['g','kg','ml','L','un'].map(u=><option key={u}>{u}</option>)}</select></label></div><label>Categoria<select required value={productDraft.category} onChange={e=>setProductDraft({...productDraft,category:e.target.value})}><option value="">Selecione</option>{['Alimentos','Bebidas','Limpeza','Higiene pessoal','Utilidades domésticas','Outros'].map(c=><option key={c}>{c}</option>)}</select></label><label>Código de barras (opcional)<input inputMode="numeric" value={productDraft.code} onChange={e=>setProductDraft({...productDraft,code:e.target.value})}/><small>Você pode cadastrar sem código.</small></label>{duplicate&&<div className="notice"><span>Este produto já está cadastrado.</span><button type="button" onClick={()=>go(`product/${duplicate.id}`)}>Ver produto</button></div>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary">Cadastrar produto</button></form>}
 {isReview&&product&&<div className="stack"><div className="progress"><span>Etapa {step} de 3</span><span>{['Sua experiência','Seus motivos','Conferir'][step-1]}</span></div><progress value={step} max={3}/><p className="review-product">{product.name}<span>{product.brand} · {product.amount}</span></p>{step===1&&([['buy','Compraria novamente?',['Sim','Talvez','Não']],['quality','Qualidade',['Baixa','Adequada','Alta']],['expectation','Expectativa',['Não atendeu','Atendeu','Superou']],['value','Custo-benefício',['Ruim','Justo','Bom']]] as const).map(([key,label,options])=><fieldset className="choice-group" key={key}><legend>{label}</legend><div>{options.map(value=><label key={value}><input type="radio" name={key} value={value} checked={draft[key]===value} onChange={()=>setDraft({...draft,[key]:value})}/><span>{value}</span></label>)}</div></fieldset>)}{step===2&&<><h2>O que chamou atenção?</h2><p className="subtitle">Escolha ao menos um aspecto.</p>{aspects.map(aspect=><div className="reason" key={aspect}><label><input type="checkbox" checked={aspect in draft.reasons} onChange={e=>{const reasons={...draft.reasons};if(e.target.checked)reasons[aspect]='';else delete reasons[aspect];setDraft({...draft,reasons});}}/>{aspect}</label>{aspect in draft.reasons&&<div className="segments">{['Positivo','Negativo'].map(v=><button key={v} className={draft.reasons[aspect]===v?'selected':''} aria-pressed={draft.reasons[aspect]===v} onClick={()=>setDraft({...draft,reasons:{...draft.reasons,[aspect]:v}})}>{v}</button>)}</div>}</div>)}<label>Comentário {draft.reasons.Outro?'(obrigatório)':'(opcional)'}<textarea rows={4} maxLength={1000} value={draft.comment} onChange={e=>setDraft({...draft,comment:e.target.value})}/><small>{draft.comment.length}/1.000 caracteres</small></label></>}{step===3&&<><Badge buy={draft.buy}/><dl>{[['Qualidade',draft.quality],['Expectativa',draft.expectation],['Custo-benefício',draft.value],...Object.entries(draft.reasons)].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{draft.comment&&<blockquote>{draft.comment}</blockquote>}<button className="text-button" onClick={()=>setStep(1)}>Corrigir respostas</button><p className="public-note">Na versão final, sua avaliação será pública com seu nome de exibição. Aqui, os dados ficam apenas nesta demonstração.</p></>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary wide" onClick={step===3?saveReview:advance}>{step===3?(editing?'Salvar alterações':'Publicar avaliação'):'Continuar'}</button></div>}
 </main>
 {!isReview&&route!=='new'&&route!=='login'&&<nav className="bottom-nav" aria-label="Navegação principal">{[['home','Início',House],['search','Buscar',MagnifyingGlass],['account','Minhas avaliações',ClockCounterClockwise]].map(([path,label,Icon])=>{const I=Icon as typeof House;return <button key={String(path)} className={(route===path||(path==='search'&&isDetail)||(path==='account'&&route==='owned'))?'active':''} aria-current={route===path?'page':undefined} onClick={()=>String(path)==='account'?requireSign('account'):go(String(path))}><I size={28}/><span>{String(label)}</span></button>;})}</nav>}
 <dialog ref={dialog} onCancel={()=>setDeleteOpen(false)} aria-labelledby="delete-title"><h2 id="delete-title">Excluir sua avaliação?</h2><p>{product?.name}</p><p>Ela será removida e não poderá ser recuperada.</p><div className="stack"><button autoFocus className="secondary" onClick={()=>setDeleteOpen(false)}>Cancelar</button><button className="primary destructive" onClick={()=>{if(network){setError('Sem conexão. Tente novamente.');return;}setProducts(ps=>ps.map(p=>p.id===id?{...p,review:undefined}:p));setDeleteOpen(false);go(`product/${id}`);setNotice('Avaliação excluída da demonstração.');}}>Excluir avaliação</button>{error&&<p role="alert" className="error">{error}</p>}</div></dialog>
 </div><details className="demo-tools"><summary>Controles da prévia</summary><p>Dados temporários: recarregar restaura os exemplos. Nenhuma alteração é enviada à API.</p><label><input type="checkbox" checked={network} onChange={e=>setNetwork(e.target.checked)}/>Simular falha de conexão</label><label><input type="checkbox" checked={failSave} onChange={e=>setFailSave(e.target.checked)}/>Simular falha ao publicar</label><button onClick={()=>{setSigned(false);setDestination(route);go('login');}}>Simular sessão expirada</button></details></div>;
}
